codecov:
  branch: development
  strict_yaml_branch: development

coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null