codecov:
  token: 0b19440d-42cf-40bb-b455-09b89e8d3010

coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 0%
        only_pulls: false
        branches: null
        flags: null
        paths: null